### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by sokbae** [SGDinference-Lab/SGDinference#8]
- Diagonal Vhat (default)
- Add confidence level
- Readme update
- Vignette update

**Comment by sokbae** [comment]
- Suppose the choice of 0 in the rss index
- Carry out scaling inside the cpp code
- Continue to update readme and vignette files
- Write more tests

**Comment by yshin12** [comment]
- Implement the new scaling algorithm to every function
- Print out the chosen confidence level
- Add more exercises on vignette and test files.

**Comment by sokbae** [comment]
All resolved
